export const mockDeals = [
  {
    id: "1",
    title: "Apple AirPods Pro (2nd Generation) - $50 Off",
    description:
      "Enjoy premium sound quality and active noise cancellation with the latest AirPods Pro, now at a special discount.",
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    imageUrl: "/placeholder.svg?height=300&width=500",
    merchant: "Amazon",
    category: "Electronics",
    tags: ["headphones", "apple", "wireless"],
    postedBy: {
      name: "TechDeals",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    votes: {
      up: 342,
      down: 12,
    },
    commentsCount: 48,
    isVerified: true,
  },
  {
    id: "2",
    title: "Nike Air Max 90 - Summer Sale",
    description:
      "Classic Nike Air Max 90 sneakers at 30% off. Multiple colors and sizes available while supplies last.",
    price: 89.99,
    originalPrice: 129.99,
    discount: 30,
    imageUrl: "/placeholder.svg?height=300&width=500",
    merchant: "Nike",
    category: "Fashion",
    tags: ["shoes", "sneakers", "sportswear"],
    postedBy: {
      name: "SneakerHead",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    votes: {
      up: 156,
      down: 5,
    },
    commentsCount: 23,
  },
  {
    id: "3",
    title: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
    description:
      "Cook meals up to 70% faster with this versatile 7-in-1 pressure cooker, slow cooker, rice cooker, and more.",
    price: 79.95,
    originalPrice: 99.95,
    discount: 20,
    imageUrl: "/placeholder.svg?height=300&width=500",
    merchant: "Walmart",
    category: "Home",
    tags: ["kitchen", "appliances", "cooking"],
    postedBy: {
      name: "HomeChef",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    votes: {
      up: 278,
      down: 8,
    },
    commentsCount: 42,
    isVerified: true,
  },
  {
    id: "4",
    title: "PlayStation 5 Digital Edition Bundle with Extra Controller",
    description:
      "Get the PS5 Digital Edition with an extra DualSense controller and 3-month PlayStation Plus subscription.",
    price: 449.99,
    originalPrice: 519.99,
    discount: 13,
    imageUrl: "/placeholder.svg?height=300&width=500",
    merchant: "Best Buy",
    category: "Electronics",
    tags: ["gaming", "console", "playstation"],
    postedBy: {
      name: "GameHunter",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    votes: {
      up: 521,
      down: 15,
    },
    commentsCount: 87,
    expiresIn: "2 days",
    isExpiring: true,
  },
  {
    id: "5",
    title: "Kindle Paperwhite E-reader - Waterproof with 2x Storage",
    description:
      "The thinnest, lightest Kindle Paperwhite yet with a flush-front design and 300 ppi glare-free display.",
    price: 129.99,
    originalPrice: 149.99,
    discount: 13,
    imageUrl: "/placeholder.svg?height=300&width=500",
    merchant: "Amazon",
    category: "Electronics",
    tags: ["books", "e-reader", "kindle"],
    postedBy: {
      name: "BookWorm",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    votes: {
      up: 187,
      down: 3,
    },
    commentsCount: 31,
  },
  {
    id: "6",
    title: "Samsonite Omni PC Hardside Expandable Luggage Set",
    description:
      '3-piece set including 20" carry-on and 24" and 28" spinners with TSA locks and scratch-resistant exterior.',
    price: 299.99,
    originalPrice: 569.99,
    discount: 47,
    imageUrl: "/placeholder.svg?height=300&width=500",
    merchant: "Macy's",
    category: "Travel",
    tags: ["luggage", "travel", "suitcase"],
    postedBy: {
      name: "Wanderlust",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    votes: {
      up: 203,
      down: 7,
    },
    commentsCount: 35,
    isVerified: true,
  },
  {
    id: "7",
    title: "Dyson V11 Torque Drive Cordless Vacuum Cleaner",
    description: "Powerful suction for deep cleaning, with intelligent reports and up to 60 minutes of run time.",
    price: 499.99,
    originalPrice: 699.99,
    discount: 29,
    imageUrl: "/placeholder.svg?height=300&width=500",
    merchant: "Target",
    category: "Home",
    tags: ["vacuum", "cleaning", "dyson"],
    postedBy: {
      name: "CleanFreak",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    votes: {
      up: 312,
      down: 18,
    },
    commentsCount: 56,
  },
  {
    id: "8",
    title: "Bose QuietComfort 45 Noise Cancelling Headphones",
    description:
      "Premium noise cancelling headphones with high-fidelity audio and comfortable design for all-day wear.",
    price: 279.99,
    originalPrice: 329.99,
    discount: 15,
    imageUrl: "/placeholder.svg?height=300&width=500",
    merchant: "Best Buy",
    category: "Electronics",
    tags: ["headphones", "audio", "noise-cancelling"],
    postedBy: {
      name: "AudioPhile",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    votes: {
      up: 245,
      down: 9,
    },
    commentsCount: 38,
    expiresIn: "1 day",
    isExpiring: true,
  },
]
